function allSongs(speed = 300, baseCord = 3) {
  let songs = [
    {
      name: "Für Elise",
      min_cord: 2,
      max_cord: pianoData.length - 1,
      def_cord: 4,
      notes: [
        { octave: `c${baseCord + 1}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord + 1}_d_sharp`, duration: speed, letter: "D#" },
        { octave: `c${baseCord + 1}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord + 1}_d_sharp`, duration: speed, letter: "D#" },
        { octave: `c${baseCord + 1}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "B" },
        { octave: `c${baseCord + 1}_d`, duration: speed, letter: "D" },
        { octave: `c${baseCord + 1}_c`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_a`, duration: speed * 2, letter: "A" },

        { octave: `c${baseCord}_c`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "A" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "B" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord}_g_sharp`, duration: speed, letter: "G#" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "B" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord + 1}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord + 1}_d_sharp`, duration: speed, letter: "D#" },
        { octave: `c${baseCord + 1}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord + 1}_d_sharp`, duration: speed, letter: "D#" },
        { octave: `c${baseCord + 1}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "B" },
        { octave: `c${baseCord + 1}_d`, duration: speed, letter: "D" },
        { octave: `c${baseCord + 1}_c`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_a`, duration: speed * 2, letter: "A" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "A" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "B" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "E" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "B" },
        { octave: `c${baseCord}_a`, duration: speed * 2, letter: "A" },
      ],
    },
   
    {
      name: "Harry Potter Theme",
      min_cord: 2,
      max_cord: pianoData.length - 1,
      def_cord: 5,
      def_speed: 200,
      notes: [
        { octave: `c${baseCord - 1}_b`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 3, letter: "E" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "A" },
        { octave: `c${baseCord}_f_sharp`, duration: speed * 2, letter: "F" },
        { octave: `c${baseCord}_e`, duration: speed * 3, letter: "B" },
        { octave: `c${baseCord}_b`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 5, letter: "F" },
        { octave: `c${baseCord}_f_sharp`, duration: speed * 6, letter: "E" },

        { octave: `c${baseCord}_e`, duration: speed * 2.5, letter: "C" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "B" },
        { octave: `c${baseCord}_f_sharp`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_d_sharp`, duration: speed * 2.5, letter: "D" },
        { octave: `c${baseCord}_f`, duration: speed * 2, letter: "C" },
        { octave: `c${baseCord - 1}_b`, duration: speed * 6, letter: "C" },

        { octave: `c${baseCord - 1}_b`, duration: speed * 2, letter: "C" },
        { octave: `c${baseCord}_e`, duration: speed * 3, letter: "C" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_f_sharp`, duration: speed * 2, letter: "C" },
        { octave: `c${baseCord}_e`, duration: speed * 2.5, letter: "C" },
        { octave: `c${baseCord}_b`, duration: speed * 2, letter: "C" },
        { octave: `c${baseCord + 1}_d`, duration: speed * 2.5, letter: "C" },
        {
          octave: `c${baseCord + 1}_c_sharp`,
          duration: speed * 2,
          letter: "C",
        },
        { octave: `c${baseCord + 1}_c`, duration: speed * 2.5, letter: "C" },
        { octave: `c${baseCord}_g`, duration: speed * 2, letter: "C" },
        { octave: `c${baseCord + 1}_c`, duration: speed * 2.5, letter: "C" },
        { octave: `c${baseCord}_b`, duration: speed, letter: "C" },
        { octave: `c${baseCord}_a_sharp`, duration: speed * 2, letter: "C" },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 3,
          letter: "C",
        },
        { octave: `c${baseCord}_g`, duration: speed * 2, letter: "C" },
        { octave: `c${baseCord}_e`, duration: speed * 6, letter: "C" },
      ],
    },

    {
      name: "Game of Thrones Theme",
      min_cord: 2,
      max_cord: pianoData.length - 1,
      def_cord: 5,
      def_speed: 200,
      notes: [
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c_sharp`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c_sharp`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c_sharp`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c_sharp`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 6, letter: "G" },

        { octave: `c${baseCord - 1}_a`, duration: speed * 6, letter: "G" },

        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed * 4, letter: "G" },

        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_b`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord - 1}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_b`, duration: speed, letter: "G" },

        { octave: `c${baseCord - 1}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_b`, duration: speed, letter: "G" },

        { octave: `c${baseCord - 1}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_b`, duration: speed, letter: "G" },

        { octave: `c${baseCord - 1}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_g`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord - 1}_g`, duration: speed * 4, letter: "G" },

        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_b`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 3, letter: "G" },

        { octave: `c${baseCord - 1}_g`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },

        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord - 1}_b`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 3, letter: "G" },

        { octave: `c${baseCord - 1}_g`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed * 2, letter: "G" },
      ],
    },
    {
      name: "Tojimari",
      min_cord: 2,
      max_cord: pianoData.length,
      def_cord: 4,
      def_speed: 200,
      notes: [
        { octave: `c${baseCord}_d`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord}_d`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord-2}_d`, duration: speed * 0, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord-2}_d`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord-2}_d`, duration: speed * 0, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord-2}_d`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord}_a`, duration: speed * 4, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*4, letter: "G" },

        { octave: `c${baseCord-1}_d`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord-1}_f`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord-1}_d`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord-1}_f`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord-1}_d`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord-1}_f`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },

        { octave: `c${baseCord-1}_d`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed * 3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord-1}_f`, duration: 0, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord - 1}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed * 2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed * 8, letter: "G" },
        
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },

        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },

        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },

        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },

        { octave: `c${baseCord+1}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },
        
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },

        { octave: `c${baseCord+1}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*6, letter: "G" },
        
        
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*5, letter: "G" },
        
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },

        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_f`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord+1}_e`, duration: speed*3, letter: "G" },

        { octave: `c${baseCord+1}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },

        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },

        { octave: `c${baseCord+1}_d`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*5, letter: "G" },
        
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*8, letter: "G" },

        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*8, letter: "G" },
        
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_e`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_c`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_d`, duration: speed*4, letter: "G" },
        
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*5, letter: "G" },
        
        
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*4, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord+1}_c`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*2, letter: "G" },
        { octave: `c${baseCord}_f`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_g`, duration: speed*3, letter: "G" },
        { octave: `c${baseCord}_a`, duration: speed*8, letter: "G" },
      ],
    },
    {
      name: "KGF Theme Music",
      min_cord: 2,
      max_cord: pianoData.length,
      def_speed: "270",
      notes: [
        // phase 1 circle1
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 2.25,
          letter: "",
        },

        // phase 1 circle2
        // 2nd
        {
          octave: `c${baseCord}_c`,
          duration: speed,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 2.25,
          letter: "",
        },

        // phase 1 circle1
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 2,
          letter: "",
        },
        // core
        // 3rd
        {
          octave: `c${baseCord}_c`,
          duration: speed,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_d_sharp`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_e`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_d_sharp`,
          duration: speed,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 1.125,
          letter: "",
        },

        // phase1 circle1
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 2.25,
          letter: "",
        },

        // phase 1 circle2
        // 2nd
        {
          octave: `c${baseCord}_c`,
          duration: speed,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 2.25,
          letter: "",
        },

        // phase1 circle1
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord - 1}_a_sharp`,
          duration: speed * 2.25,
          letter: "",
        },

        // 5rd
        {
          octave: `c${baseCord}_c`,
          duration: speed,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 2,
          letter: "",
        },
        {
          octave: `c${baseCord}_d_sharp`,
          duration: speed * 1.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_e`,
          duration: speed * 0.5,
          letter: "",
        },
        {
          octave: `c${baseCord}_d_sharp`,
          duration: speed,
          letter: "",
        },
        {
          octave: `c${baseCord}_c_sharp`,
          duration: speed * 1.125,
          letter: "",
        },
        {
          octave: `c${baseCord}_c`,
          duration: speed,
          letter: "",
        },
      ],
    },
    {
      name: "dha pa dha ma",
      min_cord: 2,
      max_cord: pianoData.length,
      def_cord: 4,
      def_speed: 300,
      notes: [
        { octave: `c${baseCord}_f_sharp`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "pa" },
        { octave: `c${baseCord}_f_sharp`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_d_sharp`, duration: speed*2, letter: "ma" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "pa" },
        { octave: `c${baseCord}_d`, duration: speed*4, letter: "Ga" },
        { octave: `c${baseCord}_d_sharp`, duration: speed*2, letter: "ma" },
        { octave: `c${baseCord}_f_sharp`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_f_sharp`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_f`, duration: speed*4, letter: "pa" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "ga" },
        { octave: `c${baseCord}_d_sharp`, duration: speed*2, letter: "ma" },
        { octave: `c${baseCord-1}_b`, duration: speed*2, letter: "ra" },
        { octave: `c${baseCord-1}_a_sharp`, duration: speed*2, letter: "sa" },
        
        { octave: `c${baseCord-1}_a_sharp`, duration: speed*2, letter: "sa" },
        { octave: `c${baseCord-1}_b`, duration: speed*2, letter: "re" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "ga" },
        { octave: `c${baseCord}_d_sharp`, duration: speed*2, letter: "ma" },
        { octave: `c${baseCord}_f`, duration: speed*4, letter: "pa" },
        { octave: `c${baseCord}_d_sharp`, duration: speed*2, letter: "ma" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "pa" },
        { octave: `c${baseCord}_a_sharp`, duration: speed*2, letter: "sa" },
        { octave: `c${baseCord}_a`, duration: speed*2, letter: "ni" },
        { octave: `c${baseCord}_f_sharp`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_f`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_d_sharp`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord}_d`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord-1}_b`, duration: speed*2, letter: "dha" },
        { octave: `c${baseCord-1}_a_sharp`, duration: speed*2, letter: "dha" },

      ]
    }
  ];

  return songs;
}
